platform :ios, '6.0'
pod 'MagicalRecord',       			'~> 2.1'
pod 'AFNetworking',  				'~> 1.3.2'
pod 'AFHTTPRequestOperationLogger', '~> 1.0.0'
pod 'QuickDialog',					'~> 0.8'
pod 'BlocksKit',					'~> 1.8.2'
pod 'CocoaLumberjack',              '~> 1.6.2'
pod 'MBProgressHUD',                '~> 0.7'
